array = ["*                *","**              **","***            ***","****          ****","*****        *****","******      ******","*******    *******","********  ********","******************"]
print(array[0])
print(array[1])
print(array[2])
print(array[3])
print(array[4])
print(array[5])
print(array[6])
print(array[7])
print(array[8])
